id: P008231
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 13:09:24.755727
source_metadata:
  id: bdr:W1KG20956
  title: སྟོན་པ་སངས་རྒྱས་ཤཱཀྱ་ཐུབ་པའི་རྣམ་ཐར།
  author: ''
  volumes:
    e4ea2dec42704fdabd5a5c110740bd7a:
      image_group_id: I1KG20976
      title: ''
      volume_number: 1
      total_pages: 136
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
